# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 4

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }} 

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: senecatest
          POSTGRES_DB: senecatest
          POSTGRES_USER: senecatest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Connect to PostgreSQL
        run: psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -f "./docker/dbschema.sql"
        env:
          POSTGRES_USER: "senecatest"
          POSTGRES_DB: "senecatest"

